# Generated by Django 3.2.9 on 2021-11-10 19:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_en', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('provider_image', models.ImageField(blank=True, upload_to='')),
                ('provider_logo', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance_provider',
            },
        ),
        migrations.CreateModel(
            name='InsurancePackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('insurance_type', models.CharField(choices=[('health', 'health'), ('life', 'life')], max_length=20)),
                ('package_type', models.CharField(choices=[('minimal', 'minimal'), ('basic', 'basic'), ('improved', 'improved')], max_length=20)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.insuranceprovider')),
            ],
            options={
                'db_table': 'insurance_package',
            },
        ),
    ]
