# Generated by Django 3.2.9 on 2021-11-09 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprovider',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='key',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='logo_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='price_last_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
