# Generated by Django 3.2.9 on 2021-11-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20211110_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprovider',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
