# Generated by Django 3.2.9 on 2021-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20211109_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovider',
            name='price_last_updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
