# Generated by Django 3.2.9 on 2021-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20211112_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
