# Generated by Django 3.2.9 on 2021-11-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20211112_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='key',
        ),
    ]
