# Generated by Django 3.2.9 on 2021-11-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_remove_insuranceprovider_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
