# Generated by Django 3.2.9 on 2021-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_insurancepackage_price_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepackage',
            name='insurance_type',
            field=models.CharField(choices=[('health', 'health'), ('life', 'life')], max_length=20),
        ),
    ]
