# Generated by Django 3.2.9 on 2021-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_auto_20211116_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_logo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
