# Generated by Django 3.2.9 on 2021-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20211117_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepackage',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
