# Generated by Django 3.2.9 on 2021-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_alter_insurancepackage_price_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprovider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
