# Generated by Django 3.2.9 on 2021-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_auto_20211124_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepackage',
            name='is_best_offer',
            field=models.BooleanField(default=False),
        ),
    ]
