# Generated by Django 3.2.9 on 2021-11-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_userfeedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
