# Generated by Django 3.2.9 on 2021-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_userfeedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
