# Generated by Django 3.2.9 on 2021-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_userfeedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
