# Generated by Django 3.2.9 on 2021-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='num_beneficiaries',
            field=models.PositiveIntegerField(default=1, help_text='Number of beneficiaries for the customer'),
        ),
    ]
